apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-db
  template:
    metadata:
      labels:
        app: workout-db
    spec:
      containers:
        - name: workout-db
          image: mongo:latest
---
apiVersion: v1
kind: Service
metadata:
  name: workout-db-srv
spec:
  selector:
    app: workout-db
  ports:
    - name: workout-db
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: workout-db-nodeport
spec:
  type: NodePort
  selector:
    app: workout-db
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 27017
      targetPort: 27017
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
